[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Cr1oArc-Dark-Orange
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Cr1oArc-Dark-Orange
GtkTheme=Cr1oArc-Dark-Orange
IconTheme=Cr1oArc-Dark-Orange
MetacityTheme=Cr1oArc-Dark-Orange
