"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$directory$os$git_branch$git_status$nodejs$rust$golang$php $character"

[os]
disabled = false
format = "[$symbol](#blue) "

[os.symbols]
Ubuntu  = "󰕈"
Artix   = "󰣇"
Arch    = "󰣇"
CachyOS = "󰣇"
Macos   = ""

[directory]
format            = "[$path](cyan) "
truncation_length = 4
truncate_to_repo  = true

[git_branch]
symbol = ""
format = "[$symbol $branch](bold purple) "

[git_status]
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bold cyan)"
behind     = "[⇣$count ](bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold cyan)"
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
untracked  = "[?$count ](bold white)"
deleted    = "[✘$count ](bold red)"
conflicted = "[⚡$count ](bold red)"

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[rust]
symbol = ""
format = "[$symbol $version](red) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[php]
symbol = ""
format = "[$symbol $version](purple) "

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](blue)"
