# Tema generado automáticamente por Matugen
background            #17130d
foreground            #ebe1d6
cursor                #f5bd63
selection_background  #584322
selection_foreground  #fbdbaf

# Paleta de colores ANSI de 16 colores
color0  #120e08
color8  #39342d

color1  #ffb4ab
color9  #93000a

color2  #f5bd63
color10 #b98833

color3  #becf76
color11 #889846

color4  #e0c297
color12 #584322

color5  #7f5600
color13 #ebe1d6

color6  #9c8f7e
color14 #4f4537

color7  #ebe1d6
color15 #d3c4b2